import { Geist, Geist_Mono } from "next/font/google";
import { Syne } from 'next/font/google';
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
const syne = Syne({
  subsets: ['latin'],
  weight: ['400', '600', '700'], // choose what you need
  variable: '--font-syne',
});


const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">

      <body
        className={`${geistSans.variable} ${geistMono.variable}  ${syne.variable} antialiased  `}
      >
        {children}
      </body>
    </html>
  );
}
